name: Deploy Go Lambdas to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - name: Install AWS SAM CLI
        run: |
          sudo pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Go application in 'auth' directory
        run: |
          cd auth
          go mod tidy
          go build -o main main.go
          cd ..

      - name: Build Go application in 'hello-world' directory
        run: |
          cd hello-world
          go mod tidy
          go build -o main main.go
          cd ..

      - name: Build and Deploy SAM Application
        run: |
          sam build
          sam deploy
